kind: Secret
apiVersion: v1
metadata:
  name: mariadb-env
  namespace: tua03
data:
  MYSQL_DATABASE: dHVhMDM=
  MYSQL_PASSWORD: dHVhMDM=
  MYSQL_ROOT_PASSWORD: dHVhMDM=
  MYSQL_USER: dHVhMDM=
type: Opaque
