global:
  scrape_interval: 15s
  evaluation_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: "wildfly"
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["wildfly:9990"]
