/* tslint:disable */
/* eslint-disable */
/**
 * Deployed Resources
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AccountPersonalDetailsDto
 */
export interface AccountPersonalDetailsDto {
    /**
     * 
     * @type {string}
     * @memberof AccountPersonalDetailsDto
     */
    firstname?: any;
    /**
     * 
     * @type {string}
     * @memberof AccountPersonalDetailsDto
     */
    contactNumber?: any;
    /**
     * 
     * @type {string}
     * @memberof AccountPersonalDetailsDto
     */
    lastname?: any;
}
