/* tslint:disable */
/* eslint-disable */
/**
 * ssbd06 application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AccountDto
 */
export interface AccountDto {
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    firstname?: any;
    /**
     * 
     * @type {any}
     * @memberof AccountDto
     */
    lastFailedLoginDate?: any;
    /**
     * 
     * @type {any}
     * @memberof AccountDto
     */
    lastSuccessfulLoginDate?: any;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    language?: any;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    lastSuccessfulLoginIpAddress?: any;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    login?: any;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    lastFailedLoginIpAddress?: any;
    /**
     * 
     * @type {boolean}
     * @memberof AccountDto
     */
    confirmed?: any;
    /**
     * 
     * @type {number}
     * @memberof AccountDto
     */
    version?: any;
    /**
     * 
     * @type {boolean}
     * @memberof AccountDto
     */
    enabled?: any;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    lastname?: any;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    themeColor?: any;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    contactNumber?: any;
    /**
     * 
     * @type {string}
     * @memberof AccountDto
     */
    email?: any;
}
