/* tslint:disable */
/* eslint-disable */
/**
 * Deployed Resources
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface HotelDto
 */
export interface HotelDto {
    /**
     * 
     * @type {string}
     * @memberof HotelDto
     */
    image?: any;
    /**
     * 
     * @type {string}
     * @memberof HotelDto
     */
    address?: any;
    /**
     * 
     * @type {string}
     * @memberof HotelDto
     */
    cityName?: any;
    /**
     * 
     * @type {string}
     * @memberof HotelDto
     */
    name?: any;
    /**
     * 
     * @type {any}
     * @memberof HotelDto
     */
    rating?: any;
    /**
     * 
     * @type {string}
     * @memberof HotelDto
     */
    description?: any;
    /**
     * 
     * @type {number}
     * @memberof HotelDto
     */
    id?: any;
    /**
     * 
     * @type {number}
     * @memberof HotelDto
     */
    version?: any;
}
