/* tslint:disable */
/* eslint-disable */
/**
 * Deployed Resources
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LoginDataDto
 */
export interface LoginDataDto {
    /**
     * 
     * @type {string}
     * @memberof LoginDataDto
     */
    password?: any;
    /**
     * 
     * @type {string}
     * @memberof LoginDataDto
     */
    login?: any;
}
