/* tslint:disable */
/* eslint-disable */
/**
 * Deployed Resources
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface NewBookingDto
 */
export interface NewBookingDto {
    /**
     * 
     * @type {Array&lt;MicroBoxes&gt;}
     * @memberof NewBookingDto
     */
    boxes?: any;
    /**
     * 
     * @type {any}
     * @memberof NewBookingDto
     */
    dateTo?: any;
    /**
     * 
     * @type {any}
     * @memberof NewBookingDto
     */
    dateFrom?: any;
}
