/* tslint:disable */
/* eslint-disable */
/**
 * Deployed Resources
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface NewRatingDto
 */
export interface NewRatingDto {
    /**
     * 
     * @type {number}
     * @memberof NewRatingDto
     */
    rate?: any;
    /**
     * 
     * @type {string}
     * @memberof NewRatingDto
     */
    comment?: any;
    /**
     * 
     * @type {number}
     * @memberof NewRatingDto
     */
    bookingId?: any;
}
