/* tslint:disable */
/* eslint-disable */
/**
 * ssbd06 application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface NewBoxDto
 */
export interface NewBoxDto {
    /**
     * 
     * @type {any}
     * @memberof NewBoxDto
     */
    price?: any;
    /**
     * 
     * @type {string}
     * @memberof NewBoxDto
     */
    animalType?: any;
    /**
     * 
     * @type {number}
     * @memberof NewBoxDto
     */
    hotelId?: any;
}
