/* tslint:disable */
/* eslint-disable */
/**
 * ssbd06 application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PasswordChangeOtherDto
 */
export interface PasswordChangeOtherDto {
    /**
     * 
     * @type {string}
     * @memberof PasswordChangeOtherDto
     */
    login?: any;
    /**
     * 
     * @type {string}
     * @memberof PasswordChangeOtherDto
     */
    givenPassword?: any;
}
