/* tslint:disable */
/* eslint-disable */
/**
 * ssbd06 application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RatingDto
 */
export interface RatingDto {
    /**
     * 
     * @type {number}
     * @memberof RatingDto
     */
    rate?: any;
    /**
     * 
     * @type {string}
     * @memberof RatingDto
     */
    comment?: any;
    /**
     * 
     * @type {number}
     * @memberof RatingDto
     */
    id?: any;
    /**
     * 
     * @type {number}
     * @memberof RatingDto
     */
    version?: any;
    /**
     * 
     * @type {number}
     * @memberof RatingDto
     */
    bookingId?: any;
}
