/* tslint:disable */
/* eslint-disable */
/**
 * Deployed Resources
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ReportRowDto
 */
export interface ReportRowDto {
    /**
     * 
     * @type {number}
     * @memberof ReportRowDto
     */
    id?: any;
    /**
     * 
     * @type {number}
     * @memberof ReportRowDto
     */
    dateFrom?: any;
    /**
     * 
     * @type {number}
     * @memberof ReportRowDto
     */
    dateTo?: any;
    /**
     * 
     * @type {string}
     * @memberof ReportRowDto
     */
    status?: any;
    /**
     * 
     * @type {any}
     * @memberof ReportRowDto
     */
    price?: any;
    /**
     * 
     * @type {number}
     * @memberof ReportRowDto
     */
    rating?: any;
    /**
     * 
     * @type {string}
     * @memberof ReportRowDto
     */
    ownerLogin?: any;
}
