/* tslint:disable */
/* eslint-disable */
/**
 * Deployed Resources
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateHotelDto
 */
export interface UpdateHotelDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateHotelDto
     */
    image?: any;
    /**
     * 
     * @type {string}
     * @memberof UpdateHotelDto
     */
    address?: any;
    /**
     * 
     * @type {string}
     * @memberof UpdateHotelDto
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof UpdateHotelDto
     */
    description?: any;
    /**
     * 
     * @type {number}
     * @memberof UpdateHotelDto
     */
    cityId?: any;
}
