/* tslint:disable */
/* eslint-disable */
/**
 * Deployed Resources
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateBoxDto
 */
export interface UpdateBoxDto {
    /**
     * 
     * @type {any}
     * @memberof UpdateBoxDto
     */
    price?: any;
    /**
     * 
     * @type {string}
     * @memberof UpdateBoxDto
     */
    description?: any;
    /**
     * 
     * @type {number}
     * @memberof UpdateBoxDto
     */
    id?: any;
}
