version: '3.8'

services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_DATABASE: tua03
      MYSQL_USER: tua03
      MYSQL_PASSWORD: tua03
      MYSQL_ROOT_PASSWORD: tua03
    networks:
      - internal_db
    volumes:
      - ./mariadb/init:/docker-entrypoint-initdb.d:ro
      - ./mariadb/mysql:/var/lib/mysql:rw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ptua03"]
      interval: 5s
      timeout: 30s
      retries: 5

  wildfly:
    build: ./wildfly
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - internal_db
      - internal_http
    volumes:
      - ./wildfly/ssbd06.war:/opt/jboss/wildfly/standalone/deployments/ssbd06.war:ro
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080"]
      interval: 5s
      timeout: 30s
      retries: 5

  nginx:
    image: nginx
    depends_on:
      wildfly:
        condition: service_healthy
    networks:
      - internal_http
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certificate.crt:/etc/ssl/private/certificate.crt:ro
      - ./nginx/private.key:/etc/ssl/private/private.key:ro
    ports:
      - "127.0.0.1:443:443"

networks:
  internal_db: {}
  internal_http: {}