version: '3.1'

services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
