image:
  name: tua03
  tag: latest
build:
  enabled: true
  mode: s2i
  uri: 'https://github.com/TULbaghia/tua'
  output:
    kind: ImageStreamTag
    pushSecret: builder-dockercfg-kz8pw
  triggers: {}
  s2i:
    version: '25.0'
    builderImage: quay.io/wildfly/wildfly-centos7
    runtimeImage: quay.io/wildfly/wildfly-runtime-centos7
  bootableJar:
    builderImage: 'registry.access.redhat.com/ubi8/openjdk-11:latest'
deploy:
  enabled: true
  replicas: 1
  route:
    enabled: true
    tls:
      enabled: true
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  livenessProbe:
    httpGet:
      path: /health/live
      port: admin
  readinessProbe:
    httpGet:
      path: /health/ready
      port: admin
